### ISSUE TITLE
(Question): How do I get line breaks?

### ISSUE THREAD

**Issue by davidkcyip** [harshankur/officeParser#10]
Hey, so after testing this plugin, it doesn't seem to return line-breaks for files processed. How do I get the plugin to return line-breaks?

**Comment by harshankur** [comment]
Ok, I can add a config argument to the parseOffice function which I can use to return line breaks as \n in the response.

**Comment by kochecc2** [comment]
This would be helpful for my application as well.

**Comment by harshankur** [comment]
Hi, I have updated officeParser to version 4.0.4 where users have access to a config object that lets users set line breaks delimiters. The default is \n.
