### ISSUE TITLE
reading the file from the buffer

### ISSUE THREAD

**Issue by bigansh** [harshankur/officeParser#13]
how to i directly read the file from the buffer? i have the file buffer stored in the memory and want to use officePartser to directly read the file from that buffer.

**Comment by harshankur** [comment]
I can add it as a feature to accept file buffer as a parameter similar to file path.
But in the meantime, you can write the buffer to a temp local file using fs and use that to read from officeParser. Let me know if that does not work.

**Comment by harshankur** [comment]
Zyada nahi lagega. But max ye weekend tak toh lag sakta hai when I have time to work on this.

**Comment by harshankur** [comment]
@bigansh Your request changes are now available.

**Comment by bigansh** [comment]
thank you very much sir!
