### ISSUE TITLE
(Bug) Cannot convert object to primitive value

### ISSUE THREAD

**Issue by danielciuca** [harshankur/officeParser#15]
Hi, I have a problem when I parse some excel files. I get this error: 
```
TypeError: Cannot convert object to primitive value
    at Array.join
```
from
```
D:\...\files\node_modules\officeparser\officeParser.js:355
            return callback(responseText.join(" "), undefined);
```
This does not happen for all files, maybe only for very large ones?

**Comment by harshankur** [comment]
Hi @danielciuca , I have updated officeParser to version 4.0.4 where I have addressed the content extraction method. Can you check if this problem still exists? If yes, please share your file (anonymized, if possible) with me to help me debug it.
