### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nodeValue')

### ISSUE THREAD

**Issue by yejue** [harshankur/officeParser#24]
I got an error  "TypeError: Cannot read properties of undefined (reading 'nodeValue')" when i try to parse "pptx" file.
Some of my files are okay, and some are not.

**Comment by ladrians** [comment]
I have the same problem, had `4.0.5` and updated to `4.0.5` just in case with the same problem, any idea?

**Comment by harshankur** [comment]
> I got an error "TypeError: Cannot read properties of undefined (reading 'nodeValue')" when i try to parse "pptx" file. Some of my files are okay, and some are not.

@yejue Any chance you can upload any of the pptx files here (or mail to me) that were failing for you with which I can debug my code?

**Comment by gerkim62** [comment]
[11. heart.pptx](https://github.com/harshankur/officeParser/files/13805081/11.heart.pptx)

I have the same problem, the above file is giving this error for me

**Comment by yejue** [comment]
> > I got an error "TypeError: Cannot read properties of undefined (reading 'nodeValue')" when i try to parse "pptx" file. Some of my files are okay, and some are not.
> 
> @yejue Any chance you can upload any of the pptx files here (or mail to me) that were failing for you with which I can debug my code?

[cccc.pptx](https://github.com/harshankur/officeParser/files/13806774/cccc.pptx)

**Comment by harshankur** [comment]
Thank you for sharing test files for me @yejue and @gerkim62. I have fixed it. Please test it with the new version 4.0.6.
