### ISSUE TITLE
Errors with bulk processing

### ISSUE THREAD

**Issue by b-hexsoul** [harshankur/officeParser#33]
I am trying to process hundreds of documents.

Getting the following errors:

ERROR parseDocument [OfficeParser]: Error: Refusing to create a directory outside the output path.
ERROR parseDocument [OfficeParser]: Error: ENOENT: no such file or directory, lstat '/src/officeParserTemp/171639676809200209.docx'
ERROR parseDocument [OfficeParser]: Error: EEXIST: file already exists, mkdir '/src/officeParserTemp/171639676571100139.docx'

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "UnknownErrorException".] {

**Comment by MiNickel** [comment]
Did you find out what the issue was? Currently experiencing the same problem

**Comment by MiNickel** [comment]
Setting the flag to preserve the temporary files fixed it for me!

**Comment by WarrenMfg** [comment]
Similar fix for me. I replaced this line:

```js
rimraf(internalConfig.tempFilesLocation, rimrafErr => consoleError(rimrafErr, internalConfig.outputErrorToConsole));
```

with this line:
```js
fs.rmSync(filepath);
```

It keeps the `officeParserTemp` and nested `tempfiles` directories though. But that can also be changed.

**Comment by WarrenMfg** [comment]
@b-hexsoul are you using `worker_threads` by chance? I had to comment out `getNewFileName` due to duplicate file names, then prefix the file names with guids myself.
