### ISSUE TITLE
Can not use officeParser on lambda AWS

### ISSUE THREAD

**Issue by ndltuan** [harshankur/officeParser#34]
![image](https://github.com/harshankur/officeParser/assets/164287504/677a7549-5834-4a57-8a24-fd930b142470)

When I use  `officeParser` on lambda I get the above error.

**Comment by harshankur** [comment]
This will probably be solved with creating a new version of officeParser which does not use decompress but rather something that can extract text without decompressing files on the file system. I am still looking into it. I think it is possible. Look at issue #35
