### ISSUE TITLE
OutOfMemory Error processing some xlsx files

### ISSUE THREAD

**Issue by ladrians** [harshankur/officeParser#40]
I am executing a process from docker containers which need to run under low level memory, environments just using an express server and having 1GB/2GB of RAM.

Processing these attachments I get OOM error and the process cannot continue processing the files.

[EZSHARE-1333690626-13.xlsx](https://github.com/user-attachments/files/16515996/EZSHARE-1333690626-13.xlsx)
[EZSHARE-239516867-71.xlsx](https://github.com/user-attachments/files/16515997/EZSHARE-239516867-71.xlsx)

The whole container is restarted when the problem happens. Separately I loaded each file and executed the following code to get an idea of memory usage:

```typescript
const used = process.memoryUsage().heapUsed / 1024 / 1024;
console.log(`App using ${Math.floor(used)} MB`);
```

with

|filename|memory (MB)|characters retrieved|
|---|---|---|
|EZSHARE-239516867-71|4750|137694|
|EZSHARE-1333690626-13|1672|42243|

Is there a chance to check if there are some memory leak or improvement from the library standpoint? Inspecting the files the associated text is not much.

thanks in advance

**Comment by ladrians** [comment]
Any comment on this issue or idea on getting a WA?

**Comment by harshankur** [comment]
@ladrians 
I am sorry I haven't been able to look into this so far. I will try to get it fixed this week.

**Comment by ladrians** [comment]
thanks for the information, anything I can help, let me know.

**Comment by harshankur** [comment]
@ladrians 
I have had a look into these files.
There seems to be something wrong about the encoding of these files.
The internal files seem to be much bigger than usual xml files underneath the xlsx files. I am not sure, but maybe opening these files in Excel and saving again might help with reducing size. I am not sure if I can help with these files. Reading such a massing file and parsing it will cause the required memory to explode in any case.
<img width="624" alt="Screenshot 2024-10-13 at 22 35 17" src="https://github.com/user-attachments/assets/d7413939-c598-4070-9cd6-08875657a32e">
<img width="635" alt="Screenshot 2024-10-13 at 22 36 17" src="https://github.com/user-attachments/assets/f4057bc7-efba-4805-89d3-3f2904e33e4c">
