### ISSUE TITLE
Crashes NodeJs process with UnhandledPromiseRejection

### ISSUE THREAD

**Issue by juanreynolds** [harshankur/officeParser#42]
On Node 20, Ubuntu 22.04, latest officeparser.

It crashes the node process with a specific pdf file (that opens properly in a pdf viewer) with:

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "UnknownErrorException".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.14.0
Worker 507817 died with exit code 1 and signal null.

**Comment by harshankur** [comment]
@juanreynolds 
Although functions failing should ideally return on promise catch but maybe there is something missing on the error handling. I will have a look at it. Please attach your pdf file here if you can for me to debug it properly.

**Comment by juanreynolds** [comment]
@harshankur Thanks for you reply. I moved the parseOfficeAsync implementation to a thread so that the application will not crash, only the thread. This had an unintended consequence: the offending pdf now parses without issue. Can't explain it but as it works I'm not complaining.
