### ISSUE TITLE
Code hangs indefinitely without error in Azure Functions with package deployment

### ISSUE THREAD

**Issue by JonathanVelkeneers** [harshankur/officeParser#45]
## Issue
I use this package for a project that is hosted on Azure Functions. This environment has package deployment enabled, meaning the folders where the application runs are read-only.
My function invocations would start receiving timeout errors without an error in the console.
After some testing I was able to fix my issue by settings `tempFilesLocation` to a different non-readonly directory on the filesystem.

I am unable to verify the issue locally due to time constraints but I presume the `fs.mkdirSync()` call is the culprit that hangs indefinitely.
This issue is probably not unique to Azure Functions and will always occur when `tempFilesLocation ` is in a read-only folder.

## Suggestion
Maybe a check can be added on `tempFilesLocation` before it is created to ensure writing is possible and the enclosing folder is not read-only

## Reproduction

This could _probably_ be reproduced by running an application that uses this package locally in a read-only folder.

I understand my environment might not be easy to reproduce, but it is as follows:

1. Create azure function app with consumption plan (free tier available)
2. Create a zip file of your local project (include node_modules)
3. Deploy to function app ([manual method](https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#manually-uploading-a-package-to-blob-storage))
4. Attempt to read in a pdf file (i'm reading from a remote fetched buffer)

**Comment by harshankur** [comment]
Hi, I have replaced the need to extract files on the storage for officeParser. It can do it in memory now. I hope this already fixes your problem too. :)
